[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Flask-based financial risk scoring platform."
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.6",
    "flask>=3.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
